sudo: required

services:
  - docker

script:
  # Requires the image tag, in order to push it when it completes.
  # ```sh
  # travis env set DOCKER_IMAGE_TAG registry.heroku.com/project_name/web
  # ```
  - ./utils/docker-build

after_success:
  # Give these values to Travis CI. For example,
  # ```sh
  # travis env set DOCKER_USERNAME email@address
  # travis env set DOCKER_PASSWORD $(heroku auth:token)
  # travis env set DOCKER_REGISTRY registry.heroku.com
  # travis env set DOCKER_IMAGE_TAG registry.heroku.com/project_name/web
  # ```
  - ./utils/travis-docker-push
