#!/bin/bash

script_path="$(readlink -f "$0")"
# Need the script folder that this script lies in in the path.
# It contains subscripts to be called.
script_dir="$(dirname $script_path)"
# Assume project root is the parent of the util directory.
project_dir="$(dirname $script_dir)"

pushd "$project_dir" > /dev/null

# Load environment variables for building the docker image.
# This, in particular, exports the `$IMAGE_TAG`,
#   required to name the new Docker image.
source "$script_dir/build-env-file"

sudo docker build \
  --tag "$DOCKER_IMAGE_TAG" \
  .    # Note the dot at the end.

popd > /dev/null
