#!/bin/bash

script_path="$(readlink -f "$0")"
# Need the script folder that this script lies in in the path.
# It contains subscripts to be called.
script_dir="$(dirname $script_path)"
# Assume project root is the parent of the util directory.
project_dir="$(dirname $script_dir)"

pushd "$project_dir" > /dev/null

source "$script_dir/settings"
sudo docker build \
  --tag "$image_tag" \
  --build-arg PROJECT_NAME="$project_name" \
  --build-arg PORT="$port" \
  .    # Note the dot at the end.

popd > /dev/null
