#!/bin/bash

script_path="$(readlink -f "$0")"
# Need the script folder that this script lies in in the path.
# It contains subscripts to be called.
script_dir="$(dirname $script_path)"
# Assume project root is the parent of the util directory.
project_dir="$(dirname $script_dir)"

## # Environment variables to be set in Travis CI.
## # Not used in local builds.
## export DOCKER_USERNAME email@address
## export DOCKER_PASSWORD $(heroku auth:token)
## export DOCKER_REGISTRY registry.heroku.com

## # Travis CI can provide a custom image tag.
## # The following does not overwrite the given image tag.
: ${DOCKER_IMAGE_TAG=phina}
export DOCKER_IMAGE_TAG
