#!/bin/bash

script_path="$(readlink -f "$0")"
# Need the script folder that this script lies in in the path.
# It contains subscripts to be called.
script_dir="$(dirname $script_path)"
# Assume project root is the parent of the util directory.
project_dir="$(dirname $script_dir)"

# Load build environment variables from the docker image.
# This, in particular, exports the `$IMAGE_TAG`,
#   required to identify the Docker image to run,
#   and the `$PORT` variable,
#   required to publish the relevant port from the container.
source "$script_dir/build-env-file"

printf "To access the server, run\n  %s\n" \
       "xdg-open 'http://localhost:$PORT/'"
sudo docker run \
  --env-file "$project_dir/docker-env-file" \
  --interactive \
  --publish="$PORT:$PORT" \
  --rm \
  --tty \
  "$IMAGE_TAG"
